CREATE TABLE IF NOT EXISTS PROJECTS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_id ON PROJECTS (id);

INSERT INTO PROJECTS (name) VALUES ('Первая запись');

CREATE TABLE IF NOT EXISTS GOODS (
    id SERIAL PRIMARY KEY,
    project_id INTEGER REFERENCES PROJECTS(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    priority INTEGER NOT NULL,
    removed BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_goods_parameters ON GOODS (id, project_id, name);